version: "3.3"
services:
  api_gateway:
    image: nginx
    working_dir: /etc/nginx
    ports:
      - "80:80"
    volumes:
      - ./api_gw.conf:/etc/nginx/conf.d/default.conf
      - ./api_services_conf:/etc/nginx/api_services_conf
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
  auth_service:
    build: ./auth_service/
    environment:
      DB_LINK: mongodb://database:27017/auth
    volumes:
      - ./auth_service/:/usr/app
